"""baseline_schema_and_inventory_transactions

Revision ID: dd83841f8382
Revises: 
Create Date: 2026-10-06 15:40:10.659493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd83841f8382'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('previous_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('resulting_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_tx_store_product', 'inventory_transactions', ['store_id', 'product_id', 'created_at'], unique=False)
    op.create_index('idx_inv_tx_type', 'inventory_transactions', ['transaction_type'], unique=False)
    op.create_index('idx_forecasts_target_date', 'forecasts', ['target_date'], unique=False)
    op.create_index('idx_holidays_events_date', 'holidays_events', ['date'], unique=False)
    op.create_index('idx_inventory_store_product', 'inventory', ['store_id', 'product_id'], unique=False)
    op.create_index('idx_oil_prices_date', 'oil_prices', ['date'], unique=False)
    op.create_index('idx_purchase_orders_status', 'purchase_orders', ['status'], unique=False)
    op.create_index('idx_sales_history_date', 'sales_history', ['date'], unique=False)
    op.create_index('idx_sales_history_prod_date', 'sales_history', ['product_id', 'date'], unique=False)
    op.create_index('idx_sales_history_store_date', 'sales_history', ['store_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sales_history_store_date', table_name='sales_history')
    op.drop_index('idx_sales_history_prod_date', table_name='sales_history')
    op.drop_index('idx_sales_history_date', table_name='sales_history')
    op.drop_index('idx_purchase_orders_status', table_name='purchase_orders')
    op.drop_index('idx_oil_prices_date', table_name='oil_prices')
    op.drop_index('idx_inventory_store_product', table_name='inventory')
    op.drop_index('idx_holidays_events_date', table_name='holidays_events')
    op.drop_index('idx_forecasts_target_date', table_name='forecasts')
    op.drop_index('idx_inv_tx_type', table_name='inventory_transactions')
    op.drop_index('idx_inv_tx_store_product', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    # ### end Alembic commands ###
